POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhdHVAZW1haWwuY29tIiwiaWQiOjIsImlhdCI6MTY1MTA1ODM0NH0._n7ac8Mzk1MyBzT_kJApvDer5lmcR3jmfkhjxdQP5RU

{
  "author": "Yes",
  "url": "https://nice.com",
  "title": "Cool",
  "year": 1232
}