POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "Robert C. Martin",
    "url": "https://blog.cleancoder.com/uncle-bob/2018/12/17/FPvsOO-List-processing.html",
    "title": "FP vs. OO List Processing",
}